from django.urls import path

from . import views

urlpatterns = [
    path("cargo/direct-delivery/", views.cargo_direct_delivery, name="cargo-direct-delivery"),
    path("cargo/service-request/", views.cargo_service_request, name="cargo-service-request"),
    path("cargo/reference/<slug:page_key>/", views.cargo_reference_page, name="cargo-reference-page"),
    path("clearance/", views.clearance_workspace, name="clearance-workspace"),
    path("clearance/reference/<slug:page_key>/", views.clearance_reference_page, name="clearance-reference-page"),
    path("clearance/search/boe/", views.declaration_search, {"search_kind": "boe"}, name="search-boe-declaration"),
    path("clearance/search/simple-amendment/", views.declaration_search, {"search_kind": "simple-amendment"}, name="search-simple-amendment"),
    path("clearance/search/post-entry/", views.declaration_search, {"search_kind": "post-entry"}, name="search-post-entry-declaration"),
    path("clearance/create/simple-amendment/", views.declaration_create, {"create_kind": "simple-amendment"}, name="create-simple-amendment"),
    path("clearance/create/post-entry/", views.declaration_create, {"create_kind": "post-entry"}, name="create-post-entry-declaration"),
    path("single-window/", views.single_window_workspace, name="single-window-workspace"),
    path("single-window/overview/", views.single_window_overview, name="single-window-overview"),
    path("single-window/ucr/create/", views.single_window_create_ucr, name="single-window-create-ucr"),
    path("single-window/ucr/search/", views.single_window_search_ucr, name="single-window-search-ucr"),
    path("single-window/ucr/transfer/", views.single_window_reference_page, {"page_key": "transfer-ucr"}, name="single-window-transfer-ucr"),
    path("single-window/ucr/received/", views.single_window_reference_page, {"page_key": "received-ucr"}, name="single-window-received-ucr"),
    path("single-window/exporter-registration/create/", views.single_window_exporter_registration, {"mode": "create"}, name="single-window-create-exporter"),
    path("single-window/exporter-registration/search/", views.single_window_exporter_registration, {"mode": "search"}, name="single-window-search-exporter"),
    path("single-window/opt-in-out/create/", views.single_window_create_opt_in_out, name="single-window-create-opt-in-out"),
    path("single-window/opt-in-out/search/", views.single_window_search_opt_in_out, name="single-window-search-opt-in-out"),
    path("single-window/opt-in-out/submitted/", views.single_window_opt_in_out_detail, name="single-window-opt-in-out-detail"),
    path("single-window/application/preparation/create/", views.single_window_preparation_application, {"mode": "create"}, name="single-window-create-preparation-application"),
    path("single-window/application/preparation/search/", views.single_window_preparation_application, {"mode": "search"}, name="single-window-search-preparation-application"),
    path("single-window/application/master/create/", views.single_window_create_master_application, name="single-window-create-master-application"),
    path("single-window/application/master/search/", views.single_window_reference_page, {"page_key": "master-search"}, name="single-window-search-master-application"),
    path("single-window/application/consignment/create/", views.single_window_reference_page, {"page_key": "consignment-create"}, name="single-window-create-consignment-application"),
    path("single-window/application/consignment/search/", views.single_window_reference_page, {"page_key": "consignment-search"}, name="single-window-search-consignment-application"),
    path("single-window/fcie/create/", views.single_window_reference_page, {"page_key": "fcie-create"}, name="single-window-create-fcie"),
    path("single-window/fcie/search/", views.single_window_reference_page, {"page_key": "fcie-search"}, name="single-window-search-fcie"),
    path("single-window/commitment/bank/create/", views.single_window_reference_page, {"page_key": "bank-create"}, name="single-window-create-bank-registration"),
    path("single-window/commitment/bank/search/", views.single_window_reference_page, {"page_key": "bank-search"}, name="single-window-search-bank-registration"),
    path("single-window/commitment/letter/create/", views.single_window_reference_page, {"page_key": "letter-create"}, name="single-window-create-letter-commitment"),
    path("single-window/commitment/letter/search/", views.single_window_reference_page, {"page_key": "letter-search"}, name="single-window-search-letter-commitment"),
    path("single-window/previous/<slug:page_key>/", views.single_window_reference_page, name="single-window-previous-data"),
    path("portal/", views.simulator_portal, name="simulator-portal"),
    path("access/login/", views.simulator_login, name="simulator-login"),
    path("access/logout/", views.simulator_logout, name="simulator-logout"),
    path("access/request-reset/", views.simulator_reset_request, name="simulator-reset-request"),
    path("", views.scenario_list, name="scenario-list"),
    path("<uuid:version_id>/", views.scenario_detail, name="scenario-detail"),
    path("<uuid:version_id>/start/", views.scenario_start, name="scenario-start"),
    path("attempts/<uuid:attempt_id>/", views.scenario_workspace, name="scenario-workspace"),
    path("attempts/<uuid:attempt_id>/actions/<uuid:action_id>/", views.scenario_action, name="scenario-action"),
    path("attempts/<uuid:attempt_id>/hint/", views.scenario_hint, name="scenario-hint"),
    path("documents/<uuid:document_id>/pdf/", views.scenario_document_pdf, name="scenario-document-pdf"),
    path("bills-of-lading/<uuid:bill_id>/pdf/", views.bill_of_lading_pdf, name="bill-of-lading-pdf"),
    path("commercial-documents/<uuid:document_id>/pdf/", views.commercial_document_pdf, name="commercial-document-pdf"),
]
