# Generated by Django 5.2.17 on 2026-09-05 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        ('scenarios', '0002_scenariostate_one_initial_state_per_scenario_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('visible_to_student', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructor_feedback', to='scenarios.scenarioattempt')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practical_feedback_authored', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='PracticalEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_score', models.PositiveIntegerField(default=0)),
                ('maximum_score', models.PositiveIntegerField(default=0)),
                ('system_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('system_outcome', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=8)),
                ('elapsed_seconds', models.PositiveIntegerField(default=0, help_text='Informational only; never included in scoring.')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation', to='scenarios.scenarioattempt')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_outcome', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=8)),
                ('revised_outcome', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=8)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_revisions', to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='evaluations.practicalevaluation')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='CriterionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('awarded_points', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('feedback', models.TextField(blank=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_results', to='evaluations.practicalevaluation')),
            ],
            options={
                'ordering': ('criterion__order', 'criterion__title'),
            },
        ),
        migrations.CreateModel(
            name='RemediationRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('criterion_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remediation', to='evaluations.criterionresult')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_recommendations', to='evaluations.practicalevaluation')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practical_recommendations', to='learning.resource')),
                ('scenario_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practical_recommendations', to='scenarios.scenarioversion')),
            ],
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('dimension', models.CharField(choices=[('accuracy', 'Accuracy'), ('document_review', 'Document review'), ('procedure', 'Procedure'), ('decision_making', 'Decision-making'), ('correction', 'Problem correction'), ('assistance', 'Assistance required'), ('completion', 'Completion')], max_length=24)),
                ('maximum_points', models.PositiveIntegerField()),
                ('mandatory', models.BooleanField(default=False)),
                ('evaluation_rule', models.JSONField(default=dict, help_text='Validated declarative evaluation rule.')),
                ('order', models.PositiveIntegerField(default=1)),
                ('remediation_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubric_criteria', to='learning.resource')),
                ('remediation_scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remediation_criteria', to='scenarios.scenarioversion')),
            ],
            options={
                'ordering': ('order', 'title'),
            },
        ),
        migrations.AddField(
            model_name='criterionresult',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='evaluations.rubriccriterion'),
        ),
        migrations.CreateModel(
            name='RubricVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], default='draft', max_length=12)),
                ('pass_percentage', models.DecimalField(decimal_places=2, default=70, max_digits=5)),
                ('is_demonstration', models.BooleanField(default=True, help_text='Demonstration rubrics are not approved competency policy.')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='evaluations.rubric')),
                ('scenario_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rubric_version', to='scenarios.scenarioversion')),
            ],
        ),
        migrations.AddField(
            model_name='rubriccriterion',
            name='rubric_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='evaluations.rubricversion'),
        ),
        migrations.AddField(
            model_name='practicalevaluation',
            name='rubric_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='evaluations.rubricversion'),
        ),
        migrations.AddConstraint(
            model_name='criterionresult',
            constraint=models.UniqueConstraint(fields=('evaluation', 'criterion'), name='unique_evaluation_criterion_result'),
        ),
        migrations.AddConstraint(
            model_name='rubricversion',
            constraint=models.UniqueConstraint(fields=('rubric', 'version'), name='unique_rubric_version'),
        ),
        migrations.AddConstraint(
            model_name='rubriccriterion',
            constraint=models.UniqueConstraint(fields=('rubric_version', 'code'), name='unique_rubric_criterion_code'),
        ),
    ]
