# Generated by Django 5.2.17 on 2026-09-04 20:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_position', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrolment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='onboarding.enrolment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_records', to='learning.lesson')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('enrolment', 'lesson'), name='unique_lesson_progress')],
            },
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('available', 'Available'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='available', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrolment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to='onboarding.enrolment')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_records', to='learning.module')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('enrolment', 'module'), name='unique_module_progress')],
            },
        ),
    ]
