# Generated by Django 5.2.17 on 2026-09-04 21:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theory_completed_at', models.DateTimeField(blank=True, null=True)),
                ('orientation_unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('orientation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrolment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='programme_progress', to='onboarding.enrolment')),
            ],
        ),
    ]
