# Generated by Django 5.2.17 on 2026-09-25 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenarios', '0041_seed_customs_regimes_and_regime_40_cpcs'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='tax code')),
                ('name', models.CharField(max_length=120)),
                ('base', models.CharField(choices=[('cv', 'Customs Value'), ('cv_duty', 'Customs Value + Import Duty'), ('fob', 'FOB Ncy'), ('network', 'Network Charge'), ('flat', 'Flat amount')], default='cv', max_length=12)),
                ('rate', models.DecimalField(blank=True, decimal_places=3, help_text='Percent. Leave empty only for Import Duty (01): it uses the HS code duty rate.', max_digits=6, null=True)),
                ('flat_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Used when base is flat.', max_digits=14, null=True)),
                ('applies_to', models.CharField(choices=[('all', 'All goods'), ('vehicle', 'Vehicles only')], default='all', max_length=8)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('fob_ncy', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('freight_ncy', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('insurance_ncy', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('customs_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('import_duty', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('duty_hs_code', models.CharField(blank=True, max_length=10)),
                ('is_vehicle', models.BooleanField(default=False)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('rows', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='scenarios.consignmentapplication')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
