# Generated by Django 5.2.17 on 2026-09-04 20:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('assessment_type', models.CharField(choices=[('module', 'Module assessment'), ('final_theory', 'Final theory examination')], default='module', max_length=16)),
                ('pass_percentage', models.DecimalField(decimal_places=2, default=70, max_digits=5)),
                ('is_published', models.BooleanField(default=False)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='learning.module')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('question_type', models.CharField(choices=[('single', 'Single choice'), ('true_false', 'True or false')], default='single', max_length=16)),
                ('prompt', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('points', models.PositiveIntegerField(default=1)),
                ('is_published', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='assessments.question')),
                ('remediation_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_versions', to='learning.resource')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assessments.assessment')),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_items', to='assessments.questionversion')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessments.questionversion')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TheoryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted')], default='in_progress', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('maximum_score', models.PositiveIntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('outcome', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=8)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='assessments.assessment')),
                ('enrolment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='theory_attempts', to='onboarding.enrolment')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='TheoryResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('awarded_score', models.PositiveIntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.theoryattempt')),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='assessments.questionversion')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='assessments.answeroption')),
            ],
        ),
        migrations.AddConstraint(
            model_name='questionversion',
            constraint=models.UniqueConstraint(fields=('question', 'version'), name='unique_question_version'),
        ),
        migrations.AddConstraint(
            model_name='assessmentitem',
            constraint=models.UniqueConstraint(fields=('assessment', 'question_version'), name='unique_assessment_question'),
        ),
        migrations.AddConstraint(
            model_name='theoryattempt',
            constraint=models.UniqueConstraint(fields=('enrolment', 'assessment', 'attempt_number'), name='unique_theory_attempt_number'),
        ),
        migrations.AddConstraint(
            model_name='theoryresponse',
            constraint=models.UniqueConstraint(fields=('attempt', 'question_version'), name='unique_attempt_question_response'),
        ),
    ]
