# Generated by Django 5.2.17 on 2026-09-04 21:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessment_programme_version'),
        ('learning', '0001_initial'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='maximum_attempts',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited attempts.', null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='randomize_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LessonCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('after_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_checks', to='learning.contentblock')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_checks', to='learning.lesson')),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_checks', to='assessments.questionversion')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LessonCheckResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField()),
                ('is_correct', models.BooleanField(default=False)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('enrolment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_check_responses', to='onboarding.enrolment')),
                ('lesson_check', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='assessments.lessoncheck')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_check_responses', to='assessments.answeroption')),
            ],
            options={
                'ordering': ('-responded_at',),
            },
        ),
        migrations.CreateModel(
            name='TheoryAttemptItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assessments.theoryattempt')),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_items', to='assessments.questionversion')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='lessoncheck',
            constraint=models.UniqueConstraint(fields=('lesson', 'question_version'), name='unique_lesson_knowledge_check'),
        ),
        migrations.AddConstraint(
            model_name='lessoncheckresponse',
            constraint=models.UniqueConstraint(fields=('enrolment', 'lesson_check', 'attempt_number'), name='unique_lesson_check_attempt'),
        ),
        migrations.AddConstraint(
            model_name='theoryattemptitem',
            constraint=models.UniqueConstraint(fields=('attempt', 'question_version'), name='unique_attempt_question_item'),
        ),
    ]
