# Generated by Django 5.2.17 on 2026-09-05 10:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('area', models.CharField(choices=[('import', 'Import'), ('export', 'Export'), ('transit', 'Transit'), ('warehouse', 'Warehouse')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=180)),
                ('guidance', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_initial', models.BooleanField(default=False)),
                ('is_terminal', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('order', 'label'),
            },
        ),
        migrations.CreateModel(
            name='ScenarioAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField()),
                ('assistance_mode', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('competency', 'Competency assessment')], max_length=16)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=16)),
                ('state_data', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_saved_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('enrolment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scenario_attempts', to='onboarding.enrolment')),
                ('current_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='scenarios.scenariostate')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='AssistanceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('hint', 'Hint'), ('guidance', 'Guidance')], max_length=16)),
                ('context_code', models.CharField(max_length=100)),
                ('content_shown', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistance_events', to='scenarios.scenarioattempt')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ScenarioVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], default='draft', max_length=12)),
                ('assistance_mode', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('competency', 'Competency assessment')], default='beginner', max_length=16)),
                ('reference_status', models.CharField(choices=[('conceptual', 'Conceptual placeholder'), ('verified', 'Reference verified'), ('adapted', 'Deliberately adapted'), ('tbc', 'To be confirmed')], default='conceptual', max_length=16)),
                ('briefing', models.TextField()),
                ('learning_objective', models.TextField()),
                ('initial_data', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='scenarios.scenario')),
            ],
            options={
                'ordering': ('scenario__title', 'version'),
            },
        ),
        migrations.AddField(
            model_name='scenariostate',
            name='scenario_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='scenarios.scenarioversion'),
        ),
        migrations.CreateModel(
            name='ScenarioDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=180)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('learner_data', models.JSONField(blank=True, default=dict)),
                ('evaluator_data', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=1)),
                ('scenario_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='scenarios.scenarioversion')),
            ],
            options={
                'ordering': ('order', 'title'),
            },
        ),
        migrations.AddField(
            model_name='scenarioattempt',
            name='scenario_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='scenarios.scenarioversion'),
        ),
        migrations.CreateModel(
            name='ScenarioActionDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=180)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Required state-data key/value pairs.')),
                ('effects', models.JSONField(blank=True, default=dict, help_text='State-data key/value pairs applied after the action.')),
                ('success_feedback', models.TextField(blank=True)),
                ('beginner_hint', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('from_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_actions', to='scenarios.scenariostate')),
                ('to_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_actions', to='scenarios.scenariostate')),
                ('scenario_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_definitions', to='scenarios.scenarioversion')),
            ],
            options={
                'ordering': ('order', 'label'),
            },
        ),
        migrations.CreateModel(
            name='ScenarioAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('action_code', models.CharField(max_length=80)),
                ('state_before', models.CharField(max_length=80)),
                ('state_after', models.CharField(max_length=80)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('outcome_code', models.CharField(default='success', max_length=40)),
                ('feedback_shown', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_actions', to='scenarios.scenarioactiondefinition')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='scenarios.scenarioattempt')),
            ],
            options={
                'ordering': ('sequence',),
                'constraints': [models.UniqueConstraint(fields=('attempt', 'sequence'), name='unique_scenario_action_sequence')],
            },
        ),
        migrations.AddConstraint(
            model_name='scenarioversion',
            constraint=models.UniqueConstraint(fields=('scenario', 'version'), name='unique_scenario_version'),
        ),
        migrations.AddConstraint(
            model_name='scenariostate',
            constraint=models.UniqueConstraint(fields=('scenario_version', 'key'), name='unique_scenario_state_key'),
        ),
        migrations.AddConstraint(
            model_name='scenarioattempt',
            constraint=models.UniqueConstraint(fields=('enrolment', 'scenario_version', 'attempt_number'), name='unique_scenario_attempt_number'),
        ),
        migrations.AddConstraint(
            model_name='scenarioactiondefinition',
            constraint=models.UniqueConstraint(fields=('scenario_version', 'code'), name='unique_scenario_action_code'),
        ),
    ]
