# Generated by Django 5.2.17 on 2026-09-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='scenariostate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_initial', True)), fields=('scenario_version',), name='one_initial_state_per_scenario_version'),
        ),
    ]
