# Generated by Django 5.2.17 on 2026-09-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0002_scenariostate_one_initial_state_per_scenario_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarioversion',
            name='maximum_attempts',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited attempts.', null=True),
        ),
        migrations.AddField(
            model_name='scenarioversion',
            name='purpose',
            field=models.CharField(choices=[('practice', 'Practice'), ('module_assessment', 'Practical module assessment'), ('competency', 'Practical competency assessment')], default='practice', max_length=20),
        ),
    ]
