# Generated by Django 5.2.17 on 2026-09-11 11:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0008_cargo_description_and_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('invoice', 'Commercial invoice'), ('packing_list', 'Packing list')], default='invoice', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=12)),
                ('title', models.CharField(default='Fictitious commercial document', max_length=180)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('exporter_name', models.CharField(max_length=180)),
                ('exporter_address', models.TextField(blank=True)),
                ('exporter_contact', models.CharField(blank=True, max_length=180)),
                ('consignee_name', models.CharField(max_length=180)),
                ('consignee_address', models.TextField(blank=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('container_reference', models.CharField(blank=True, max_length=180)),
                ('payment_terms', models.CharField(blank=True, max_length=180)),
                ('fob', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('freight', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('insurance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_documents', to='scenarios.scenarioversion')),
            ],
            options={
                'ordering': ('-updated_at', 'title'),
            },
        ),
        migrations.CreateModel(
            name='CommercialDocumentLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('quantity_unit', models.CharField(default='pcs', max_length=32)),
                ('package_count', models.PositiveIntegerField(blank=True, null=True)),
                ('pieces_per_package', models.CharField(blank=True, max_length=80)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('weight_unit', models.CharField(default='KGM', max_length=12)),
                ('dimensions', models.CharField(blank=True, max_length=120)),
                ('hs_code', models.CharField(blank=True, max_length=24)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='scenarios.commercialdocument')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
