# Generated by Django 5.2.17 on 2026-09-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0009_commercialdocument_commercialdocumentline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialdocument',
            name='document_type',
            field=models.CharField(choices=[('invoice', 'Commercial invoice'), ('proforma_invoice', 'Proforma invoice'), ('packing_list', 'Packing list')], default='invoice', max_length=16),
        ),
    ]
