# Generated by Django 5.2.17 on 2026-09-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0010_alter_commercialdocument_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingStakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='11-character P00/C00/G00/Q00/V00 TIN, or 13-character GHA NID.', max_length=13)),
                ('name', models.CharField(max_length=180)),
                ('description', models.CharField(blank=True, max_length=180)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('code', 'name'),
                'constraints': [models.UniqueConstraint(fields=('code', 'name'), name='unique_training_stakeholder_code_name')],
            },
        ),
    ]
