# Generated by Django 5.2.17 on 2026-09-18 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0012_seed_training_stakeholders'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingStakeholderName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='trainingstakeholder',
            name='unique_training_stakeholder_code_name',
        ),
        migrations.AddField(
            model_name='trainingstakeholder',
            name='merged_into',
            field=models.ForeignKey(blank=True, help_text="Optional: this code resolves to the selected surviving TIN. The survivor's details take precedence.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_codes', to='scenarios.trainingstakeholder'),
        ),
        migrations.AddField(
            model_name='trainingstakeholder',
            name='roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trainingstakeholder',
            name='tin_type',
            field=models.CharField(choices=[('P00', 'Individual / sole proprietor (P00)'), ('C00', 'Company / partnership (C00)'), ('G00', 'Government agency (G00)'), ('Q00', 'Foreign mission (Q00)'), ('V00', 'Public institution / trust / co-operative (V00)'), ('GHA', 'National ID (GHA)')], default='C00', max_length=3),
        ),
        migrations.AlterField(
            model_name='trainingstakeholder',
            name='code',
            field=models.CharField(blank=True, help_text='11-character TIN or 13-character GHA NID.', max_length=13, unique=True),
        ),
        migrations.AddField(
            model_name='trainingstakeholdername',
            name='stakeholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_names', to='scenarios.trainingstakeholder'),
        ),
        migrations.AddConstraint(
            model_name='trainingstakeholdername',
            constraint=models.UniqueConstraint(fields=('stakeholder', 'name'), name='unique_stakeholder_additional_name'),
        ),
    ]
