# Generated by Django 5.2.17 on 2026-09-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0013_trainingstakeholdername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingstakeholdername',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trainingstakeholdername',
            name='roles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
