# Generated by Django 5.2.17 on 2026-09-18 09:53

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0016_consolidate_duplicate_stakeholder_names'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trainingstakeholder',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='unique_training_tin_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='trainingstakeholdername',
            constraint=models.UniqueConstraint(models.F('stakeholder'), django.db.models.functions.text.Lower('name'), name='unique_stakeholder_name_case_insensitive'),
        ),
    ]
