# Generated by Django 5.2.17 on 2026-09-18 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0017_trainingstakeholder_unique_training_tin_case_insensitive_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trainingstakeholdername',
            name='unique_stakeholder_additional_name',
        ),
        migrations.RemoveConstraint(
            model_name='trainingstakeholdername',
            name='unique_stakeholder_name_case_insensitive',
        ),
    ]
