# Generated by Django 5.2.17 on 2026-09-18 14:44

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0019_restore_distinct_aster_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24)),
                ('name', models.CharField(max_length=180)),
                ('country_code', models.CharField(default='GH', max_length=2)),
                ('address', models.TextField()),
                ('contact_name', models.CharField(max_length=180)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_service_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('code', 'name'),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('owner'), condition=models.Q(('owner__isnull', False)), name='unique_training_provider_per_owner'), models.UniqueConstraint(django.db.models.functions.text.Lower('code'), condition=models.Q(('owner__isnull', True)), name='unique_admin_training_provider_code')],
            },
        ),
    ]
