# Generated by Django 5.2.17 on 2026-09-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0020_trainingserviceprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingserviceprovider',
            name='contact_designation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
