# Generated by Django 5.2.17 on 2026-09-18 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0023_optional_provider_contact_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UcrDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_no', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('ucr_no', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=12)),
                ('regime', models.CharField(max_length=2)),
                ('show_provider', models.BooleanField(default=True)),
                ('declarant_code', models.CharField(blank=True, max_length=8)),
                ('provider_code', models.CharField(blank=True, max_length=13)),
                ('provider_name', models.CharField(blank=True, max_length=180)),
                ('provider_country', models.CharField(blank=True, max_length=2)),
                ('provider_address', models.TextField(blank=True)),
                ('provider_contact', models.CharField(blank=True, max_length=180)),
                ('provider_phone', models.CharField(blank=True, max_length=40)),
                ('provider_email', models.EmailField(blank=True, max_length=254)),
                ('provider_email_2', models.EmailField(blank=True, max_length=254)),
                ('exporter_identity', models.CharField(blank=True, max_length=13)),
                ('exporter_name', models.CharField(blank=True, max_length=180)),
                ('exporter_country', models.CharField(blank=True, max_length=2)),
                ('exporter_address', models.TextField(blank=True)),
                ('exporter_phone', models.CharField(blank=True, max_length=40)),
                ('exporter_fax', models.CharField(blank=True, max_length=40)),
                ('exporter_contact', models.CharField(blank=True, max_length=180)),
                ('exporter_contact_no', models.CharField(blank=True, max_length=40)),
                ('exporter_designation', models.CharField(blank=True, max_length=100)),
                ('importer_identity', models.CharField(blank=True, max_length=180)),
                ('importer_name', models.CharField(blank=True, max_length=180)),
                ('importer_country', models.CharField(blank=True, max_length=2)),
                ('importer_address', models.TextField(blank=True)),
                ('importer_phone', models.CharField(blank=True, max_length=40)),
                ('importer_fax', models.CharField(blank=True, max_length=40)),
                ('importer_contact', models.CharField(blank=True, max_length=180)),
                ('importer_contact_no', models.CharField(blank=True, max_length=40)),
                ('importer_designation', models.CharField(blank=True, max_length=100)),
                ('goods_description', models.TextField(blank=True)),
                ('origin_country', models.CharField(blank=True, max_length=2)),
                ('destination_country', models.CharField(blank=True, max_length=2)),
                ('transport_mode', models.CharField(blank=True, max_length=40)),
                ('user_reference', models.CharField(blank=True, max_length=100)),
                ('ucr_email', models.TextField(blank=True)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ucr_declarations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('owner',), name='one_open_ucr_draft_per_learner')],
            },
        ),
    ]
