# Generated by Django 5.2.17 on 2026-09-18 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0024_ucrdeclaration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucrdeclaration',
            name='derivation',
            field=models.CharField(blank=True, choices=[('clone', 'Clone'), ('amend', 'Amendment')], max_length=8),
        ),
        migrations.AddField(
            model_name='ucrdeclaration',
            name='source_ucr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_ucrs', to='scenarios.ucrdeclaration'),
        ),
    ]
