# Generated by Django 5.2.17 on 2026-09-18 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0025_ucrdeclaration_derivation_ucrdeclaration_source_ucr'),
    ]

    operations = [
        migrations.CreateModel(
            name='UcrDocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveSmallIntegerField()),
                ('file', models.FileField(upload_to='ucr_attachments/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ucr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='scenarios.ucrdeclaration')),
            ],
            options={
                'ordering': ('row_index', 'pk'),
            },
        ),
    ]
