# Generated by Django 5.2.17 on 2026-09-18 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0026_ucrdocumentattachment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ucrdeclaration',
            name='one_open_ucr_draft_per_learner',
        ),
    ]
