# Generated by Django 5.2.17 on 2026-09-18 23:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0027_ucrdeclaration_remove_one_draft_rule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucrdeclaration',
            name='ucr_no',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='ucrdeclaration',
            constraint=models.UniqueConstraint(condition=models.Q(('ucr_no__gt', '')), fields=('ucr_no',), name='unique_ucr_number_when_issued'),
        ),
    ]
