# Generated by Django 5.2.17 on 2026-09-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0030_consignmentapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignmentapplication',
            name='consignee_warehouse',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='consignmentapplication',
            name='consignor_warehouse',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='consignmentapplication',
            name='exporter_warehouse',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='consignmentapplication',
            name='importer_warehouse',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='consignmentapplication',
            name='reference_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consignmentapplication',
            name='consignee_same',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consignmentapplication',
            name='consignor_same',
            field=models.BooleanField(default=False),
        ),
    ]
