# Generated by Django 5.2.17 on 2026-09-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0031_consignmentapplication_consignee_warehouse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GhanaHSCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('description', models.TextField()),
                ('heading_code', models.CharField(blank=True, db_index=True, max_length=4)),
                ('quantity_unit', models.CharField(blank=True, max_length=120)),
                ('import_duty', models.CharField(blank=True, max_length=24)),
                ('import_vat', models.CharField(blank=True, max_length=24)),
                ('import_excise', models.CharField(blank=True, max_length=24)),
                ('export_duty', models.CharField(blank=True, max_length=24)),
                ('nhil_rate', models.CharField(blank=True, max_length=24)),
                ('source_page', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ghana HS code',
                'verbose_name_plural': 'Ghana HS codes',
                'ordering': ('code',),
            },
        ),
    ]
