# Generated by Django 5.2.17 on 2026-09-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0033_seed_ghana_hs_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('name', models.CharField(db_index=True, max_length=180)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=2)),
                ('country_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Port code',
                'verbose_name_plural': 'Port codes',
                'ordering': ('code',),
            },
        ),
    ]
