# Generated by Django 5.2.17 on 2026-09-24 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0034_portcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='MdaAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'MDA',
                'verbose_name_plural': 'MDAs',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='MdaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('mda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='scenarios.mdaagency')),
            ],
            options={
                'ordering': ('mda__code', 'code'),
            },
        ),
        migrations.CreateModel(
            name='MdaProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='scenarios.mdaapplication')),
            ],
            options={
                'ordering': ('application__mda__code', 'application__code', 'code'),
            },
        ),
        migrations.AddConstraint(
            model_name='mdaapplication',
            constraint=models.UniqueConstraint(fields=('mda', 'code'), name='unique_application_code_per_mda'),
        ),
        migrations.AddConstraint(
            model_name='mdaprocess',
            constraint=models.UniqueConstraint(fields=('application', 'code'), name='unique_process_code_per_mda_application'),
        ),
    ]
