# Generated by Django 5.2.17 on 2026-09-24 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0036_seed_core_mdas'),
    ]

    operations = [
        migrations.CreateModel(
            name='MdaConsignmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignment_type', models.CharField(choices=[('SB', 'Sub Consignment'), ('SG', 'Single Consignment'), ('NB', 'Non B/L')], max_length=2)),
                ('master_no', models.CharField(blank=True, max_length=30)),
                ('application_no', models.CharField(editable=False, max_length=25, unique=True)),
                ('status', models.CharField(default='Draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignment_requests', to='scenarios.mdaapplication')),
                ('consignment_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mda_requests', to='scenarios.consignmentapplication')),
                ('mda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignment_requests', to='scenarios.mdaagency')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignment_requests', to='scenarios.mdaprocess')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
    ]
