# Generated by Django 5.2.17 on 2026-09-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0037_mdaconsignmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdaconsignmentrequest',
            name='additional_parties',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mdaconsignmentrequest',
            name='approval_purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mdaconsignmentrequest',
            name='approval_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mdaconsignmentrequest',
            name='approval_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mdaconsignmentrequest',
            name='form_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mdaconsignmentrequest',
            name='monthly_sequence',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='mdaconsignmentrequest',
            name='sequence_month',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True),
        ),
        migrations.AddConstraint(
            model_name='mdaconsignmentrequest',
            constraint=models.UniqueConstraint(fields=('sequence_month', 'monthly_sequence'), name='unique_mda_monthly_sequence'),
        ),
    ]
