# Generated by Django 5.2.17 on 2026-09-25 06:05

from django.db import migrations, models


def map_written_statuses_to_codes(apps, schema_editor):
    """Records created before the status codes stored the written word."""
    MdaConsignmentRequest = apps.get_model("scenarios", "MdaConsignmentRequest")
    MdaConsignmentRequest.objects.filter(status="Draft").update(status="DR")


def map_codes_to_written_statuses(apps, schema_editor):
    MdaConsignmentRequest = apps.get_model("scenarios", "MdaConsignmentRequest")
    MdaConsignmentRequest.objects.filter(status="DR").update(status="Draft")


STATUS_CHOICES = [
    ("DR", "DR, Draft"),
    ("PP", "PP, Submit - Pending Fee"),
    ("SU", "SU, Submitted"),
    ("OH", "OH, On-Hold"),
    ("QY", "QY, Query"),
    ("RJ", "RJ, Rejected"),
    ("PD", "PD, Approval - Pending Fee"),
    ("AC", "AC, Approved Checking Officer"),
    ("AV", "AV, Approved Validation Officer"),
    ("AM", "AM, Approved MDA"),
    ("AD", "AD, Approved DTRD Checking Officer"),
    ("AE", "AE, Approved DTRD Validation Officer"),
    ("AG", "AG, Approved GCUS Checking Officer"),
    ("AP", "AP, Approved"),
    ("RS", "RS, Re-Submit"),
    ("MA", "MA, Appeal"),
    ("MP", "MP, Approved Appeal"),
    ("MR", "MR, Rejected Appeal"),
    ("SC", "SC, Approved 2nd MDA Checking Officer(GCoO)"),
]


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0038_mdaconsignmentrequest_additional_parties_and_more'),
    ]

    operations = [
        migrations.RunPython(map_written_statuses_to_codes, map_codes_to_written_statuses),
        migrations.AlterField(
            model_name='mdaconsignmentrequest',
            name='status',
            field=models.CharField(choices=STATUS_CHOICES, default='DR', max_length=2),
        ),
    ]
