# Generated by Django 5.2.17 on 2026-09-25 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0039_alter_mdaconsignmentrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomsRegime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=240)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='CustomsProcedureCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('regime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_codes', to='scenarios.customsregime')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
    ]
