# Generated by Django 5.2.17 on 2026-09-25 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0041_seed_customs_regimes_and_regime_40_cpcs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoeDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_no', models.CharField(blank=True, editable=False, max_length=24, unique=True)),
                ('regime', models.CharField(blank=True, max_length=2)),
                ('cpc', models.CharField(blank=True, max_length=12)),
                ('zone', models.CharField(blank=True, max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('assessed', 'Assessed'), ('accepted', 'Accepted')], default='draft', max_length=12)),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('assessment_rows', models.JSONField(blank=True, null=True)),
                ('assessment_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boe_declarations', to='scenarios.mdaconsignmentrequest')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boe_declarations', to=settings.AUTH_USER_MODEL)),
                ('ucr', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='boe_declaration', to='scenarios.ucrdeclaration')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BoeStageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boe_stage_events', to=settings.AUTH_USER_MODEL)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_events', to='scenarios.boedeclaration')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
    ]
