# Generated by Django 5.2.17 on 2026-09-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0042_boedeclaration_boestageevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoeSequence',
            fields=[
                ('key', models.CharField(default='boe', editable=False, max_length=20, primary_key=True, serialize=False)),
                ('current_value', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
