# Generated by Django 5.2.17 on 2026-09-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0043_boesequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSequence',
            fields=[
                ('key', models.CharField(default='job', editable=False, max_length=20, primary_key=True, serialize=False)),
                ('current_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='boedeclaration',
            name='job_no',
            field=models.CharField(blank=True, editable=False, max_length=24, unique=True),
        ),
    ]
