# Generated by Django 5.2.17 on 2026-09-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0044_jobsequence_boedeclaration_job_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdaconsignmentrequest',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
