# Generated by Django 5.2.17 on 2026-09-29 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0045_mdaconsignmentrequest_submitted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='boedeclaration',
            name='declaration_no',
            field=models.CharField(blank=True, editable=False, max_length=24),
        ),
        migrations.AlterField(
            model_name='boedeclaration',
            name='job_no',
            field=models.CharField(editable=False, max_length=24, unique=True),
        ),
        migrations.AddConstraint(
            model_name='boedeclaration',
            constraint=models.UniqueConstraint(condition=models.Q(('declaration_no__gt', '')), fields=('declaration_no',), name='unique_boe_number_when_issued'),
        ),
    ]
