# Generated by Django 5.2.17 on 2026-09-11 16:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentIdSequence',
            fields=[
                ('key', models.CharField(default='students', editable=False, max_length=20, primary_key=True, serialize=False)),
                ('current_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='SimulatorCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reset_requested_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simulator_credential', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
