# Generated by Django 5.2.17 on 2026-09-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentidsequence_user_student_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulatorcredential',
            name='nonce',
        ),
        migrations.AddField(
            model_name='simulatorcredential',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='simulatorcredential',
            name='revealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
