# Generated by Django 5.2.17 on 2026-09-25 15:04

from django.db import migrations, models


def blank_emails_become_null(apps, schema_editor):
    """Users created through the admin add screen carry email=""; NULLs do not collide."""
    User = apps.get_model("accounts", "User")
    User.objects.filter(email="").update(email=None)


def null_emails_become_blank(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(email=None).update(email="")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_simulatorcredential_nonce_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.RunPython(blank_emails_become_null, null_emails_become_blank),
    ]
