# Generated by Django 5.2.17 on 2026-09-05 11:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
        ('onboarding', '0002_enrolment_enrolled_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requires_instructor_approval', models.BooleanField(default=False)),
                ('certificate_template_version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programme_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='completion_policy', to='onboarding.programmeversion')),
            ],
        ),
        migrations.CreateModel(
            name='CompletionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending instructor approval'), ('completed', 'Completed')], max_length=20)),
                ('evidence_snapshot', models.JSONField(default=dict)),
                ('policy_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completion_approvals', to=settings.AUTH_USER_MODEL)),
                ('enrolment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='completion_record', to='onboarding.enrolment')),
                ('qualifying_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completion_records', to='evaluations.practicalevaluation')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('template_version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('revoked', 'Revoked')], default='issued', max_length=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('completion_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='reports.completionrecord')),
            ],
        ),
    ]
