# Generated by Django 5.2.17 on 2026-09-04 20:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisclaimerVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('is_current', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='onboarding.programme')),
            ],
            options={
                'ordering': ('programme__name', 'version'),
            },
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn')], default='active', max_length=12)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to=settings.AUTH_USER_MODEL)),
                ('programme_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='onboarding.programmeversion')),
            ],
        ),
        migrations.CreateModel(
            name='DisclaimerAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disclaimer_acceptances', to=settings.AUTH_USER_MODEL)),
                ('disclaimer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='onboarding.disclaimerversion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'disclaimer'), name='unique_disclaimer_acceptance')],
            },
        ),
        migrations.AddConstraint(
            model_name='programmeversion',
            constraint=models.UniqueConstraint(fields=('programme', 'version'), name='unique_programme_version'),
        ),
        migrations.AddConstraint(
            model_name='enrolment',
            constraint=models.UniqueConstraint(fields=('student', 'programme_version'), name='unique_student_programme_enrolment'),
        ),
    ]
